// Even Fibonacci numbers
// Problem 2 
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
// This solution is intented to be run with nodejs
//
function p2(max) {
  var acc = 0;
  var fibs = [];
  fibs.push(1);
  fibs.push(1);
  while(true) {
    var next = fibs[fibs.length - 1] + fibs[fibs.length - 2];
    if (next > max) {
      break;
    }
    fibs.push(next);
    if (next % 2 === 0) {
      acc += next;
    }
  }
  console.log(acc);
}

p2(4000000); // the answer is 4613732
